// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: internal/geoip/proto/geoip.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoIPService_Lookup_FullMethodName      = "/geoip.v1.GeoIPService/Lookup"
	GeoIPService_BatchLookup_FullMethodName = "/geoip.v1.GeoIPService/BatchLookup"
	GeoIPService_MyIP_FullMethodName        = "/geoip.v1.GeoIPService/MyIP"
	GeoIPService_GetDBInfo_FullMethodName   = "/geoip.v1.GeoIPService/GetDBInfo"
)

// GeoIPServiceClient is the client API for GeoIPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoIPServiceClient interface {
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	BatchLookup(ctx context.Context, in *BatchLookupRequest, opts ...grpc.CallOption) (*BatchLookupResponse, error)
	MyIP(ctx context.Context, in *MyIPRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	GetDBInfo(ctx context.Context, in *DBInfoRequest, opts ...grpc.CallOption) (*DBInfoResponse, error)
}

type geoIPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoIPServiceClient(cc grpc.ClientConnInterface) GeoIPServiceClient {
	return &geoIPServiceClient{cc}
}

func (c *geoIPServiceClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, GeoIPService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoIPServiceClient) BatchLookup(ctx context.Context, in *BatchLookupRequest, opts ...grpc.CallOption) (*BatchLookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchLookupResponse)
	err := c.cc.Invoke(ctx, GeoIPService_BatchLookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoIPServiceClient) MyIP(ctx context.Context, in *MyIPRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, GeoIPService_MyIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoIPServiceClient) GetDBInfo(ctx context.Context, in *DBInfoRequest, opts ...grpc.CallOption) (*DBInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DBInfoResponse)
	err := c.cc.Invoke(ctx, GeoIPService_GetDBInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoIPServiceServer is the server API for GeoIPService service.
// All implementations must embed UnimplementedGeoIPServiceServer
// for forward compatibility.
type GeoIPServiceServer interface {
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	BatchLookup(context.Context, *BatchLookupRequest) (*BatchLookupResponse, error)
	MyIP(context.Context, *MyIPRequest) (*LookupResponse, error)
	GetDBInfo(context.Context, *DBInfoRequest) (*DBInfoResponse, error)
	mustEmbedUnimplementedGeoIPServiceServer()
}

// UnimplementedGeoIPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoIPServiceServer struct{}

func (UnimplementedGeoIPServiceServer) Lookup(context.Context, *LookupRequest) (*LookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedGeoIPServiceServer) BatchLookup(context.Context, *BatchLookupRequest) (*BatchLookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchLookup not implemented")
}
func (UnimplementedGeoIPServiceServer) MyIP(context.Context, *MyIPRequest) (*LookupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyIP not implemented")
}
func (UnimplementedGeoIPServiceServer) GetDBInfo(context.Context, *DBInfoRequest) (*DBInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDBInfo not implemented")
}
func (UnimplementedGeoIPServiceServer) mustEmbedUnimplementedGeoIPServiceServer() {}
func (UnimplementedGeoIPServiceServer) testEmbeddedByValue()                      {}

// UnsafeGeoIPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoIPServiceServer will
// result in compilation errors.
type UnsafeGeoIPServiceServer interface {
	mustEmbedUnimplementedGeoIPServiceServer()
}

func RegisterGeoIPServiceServer(s grpc.ServiceRegistrar, srv GeoIPServiceServer) {
	// If the following call pancis, it indicates UnimplementedGeoIPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoIPService_ServiceDesc, srv)
}

func _GeoIPService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoIPServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoIPService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoIPServiceServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoIPService_BatchLookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchLookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoIPServiceServer).BatchLookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoIPService_BatchLookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoIPServiceServer).BatchLookup(ctx, req.(*BatchLookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoIPService_MyIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoIPServiceServer).MyIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoIPService_MyIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoIPServiceServer).MyIP(ctx, req.(*MyIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoIPService_GetDBInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoIPServiceServer).GetDBInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoIPService_GetDBInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoIPServiceServer).GetDBInfo(ctx, req.(*DBInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoIPService_ServiceDesc is the grpc.ServiceDesc for GeoIPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoIPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geoip.v1.GeoIPService",
	HandlerType: (*GeoIPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _GeoIPService_Lookup_Handler,
		},
		{
			MethodName: "BatchLookup",
			Handler:    _GeoIPService_BatchLookup_Handler,
		},
		{
			MethodName: "MyIP",
			Handler:    _GeoIPService_MyIP_Handler,
		},
		{
			MethodName: "GetDBInfo",
			Handler:    _GeoIPService_GetDBInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/geoip/proto/geoip.proto",
}
