// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.6
// source: internal/geoip/proto/geoip.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_internal_geoip_proto_geoip_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Formatted     string                 `protobuf:"bytes,7,opt,name=formatted,proto3" json:"formatted,omitempty"`
	Found         bool                   `protobuf:"varint,8,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_internal_geoip_proto_geoip_proto_rawDescGZIP(), []int{1}
}

func (x *LookupResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LookupResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *LookupResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *LookupResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *LookupResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LookupResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LookupResponse) GetFormatted() string {
	if x != nil {
		return x.Formatted
	}
	return ""
}

func (x *LookupResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type BatchLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLookupRequest) Reset() {
	*x = BatchLookupRequest{}
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLookupRequest) ProtoMessage() {}

func (x *BatchLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLookupRequest.ProtoReflect.Descriptor instead.
func (*BatchLookupRequest) Descriptor() ([]byte, []int) {
	return file_internal_geoip_proto_geoip_proto_rawDescGZIP(), []int{2}
}

func (x *BatchLookupRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type BatchLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*LookupResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchLookupResponse) Reset() {
	*x = BatchLookupResponse{}
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLookupResponse) ProtoMessage() {}

func (x *BatchLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLookupResponse.ProtoReflect.Descriptor instead.
func (*BatchLookupResponse) Descriptor() ([]byte, []int) {
	return file_internal_geoip_proto_geoip_proto_rawDescGZIP(), []int{3}
}

func (x *BatchLookupResponse) GetResults() []*LookupResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type MyIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyIPRequest) Reset() {
	*x = MyIPRequest{}
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyIPRequest) ProtoMessage() {}

func (x *MyIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyIPRequest.ProtoReflect.Descriptor instead.
func (*MyIPRequest) Descriptor() ([]byte, []int) {
	return file_internal_geoip_proto_geoip_proto_rawDescGZIP(), []int{4}
}

type DBInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBInfoRequest) Reset() {
	*x = DBInfoRequest{}
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBInfoRequest) ProtoMessage() {}

func (x *DBInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBInfoRequest.ProtoReflect.Descriptor instead.
func (*DBInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_geoip_proto_geoip_proto_rawDescGZIP(), []int{5}
}

type DBInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	BuildEpoch    int64                  `protobuf:"varint,2,opt,name=build_epoch,json=buildEpoch,proto3" json:"build_epoch,omitempty"`
	BuildDate     string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	Loaded        bool                   `protobuf:"varint,4,opt,name=loaded,proto3" json:"loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBInfoResponse) Reset() {
	*x = DBInfoResponse{}
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBInfoResponse) ProtoMessage() {}

func (x *DBInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geoip_proto_geoip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBInfoResponse.ProtoReflect.Descriptor instead.
func (*DBInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_geoip_proto_geoip_proto_rawDescGZIP(), []int{6}
}

func (x *DBInfoResponse) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *DBInfoResponse) GetBuildEpoch() int64 {
	if x != nil {
		return x.BuildEpoch
	}
	return 0
}

func (x *DBInfoResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *DBInfoResponse) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

var File_internal_geoip_proto_geoip_proto protoreflect.FileDescriptor

var file_internal_geoip_proto_geoip_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x65, 0x6f, 0x69, 0x70,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x1f, 0x0a, 0x0d,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0xdf, 0x01,
	0x0a, 0x0e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x22,
	0x26, 0x0a, 0x12, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x22, 0x49, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x79, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x42, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x81, 0x01, 0x0a, 0x0e, 0x44, 0x42, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x32, 0x90, 0x02, 0x0a, 0x0c, 0x47, 0x65, 0x6f, 0x49, 0x50,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x12, 0x17, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x65, 0x6f,
	0x69, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x12, 0x1c, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x37, 0x0a, 0x04, 0x4d, 0x79, 0x49, 0x50, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x79, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x44, 0x42, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x42, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x67, 0x65, 0x6f, 0x69, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x42, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2d, 0x64,
	0x65, 0x73, 0x69, 0x67, 0x6e, 0x2d, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x65,
	0x6f, 0x69, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_internal_geoip_proto_geoip_proto_rawDescOnce sync.Once
	file_internal_geoip_proto_geoip_proto_rawDescData []byte
)

func file_internal_geoip_proto_geoip_proto_rawDescGZIP() []byte {
	file_internal_geoip_proto_geoip_proto_rawDescOnce.Do(func() {
		file_internal_geoip_proto_geoip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_geoip_proto_geoip_proto_rawDesc), len(file_internal_geoip_proto_geoip_proto_rawDesc)))
	})
	return file_internal_geoip_proto_geoip_proto_rawDescData
}

var file_internal_geoip_proto_geoip_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_geoip_proto_geoip_proto_goTypes = []any{
	(*LookupRequest)(nil),       // 0: geoip.v1.LookupRequest
	(*LookupResponse)(nil),      // 1: geoip.v1.LookupResponse
	(*BatchLookupRequest)(nil),  // 2: geoip.v1.BatchLookupRequest
	(*BatchLookupResponse)(nil), // 3: geoip.v1.BatchLookupResponse
	(*MyIPRequest)(nil),         // 4: geoip.v1.MyIPRequest
	(*DBInfoRequest)(nil),       // 5: geoip.v1.DBInfoRequest
	(*DBInfoResponse)(nil),      // 6: geoip.v1.DBInfoResponse
}
var file_internal_geoip_proto_geoip_proto_depIdxs = []int32{
	1, // 0: geoip.v1.BatchLookupResponse.results:type_name -> geoip.v1.LookupResponse
	0, // 1: geoip.v1.GeoIPService.Lookup:input_type -> geoip.v1.LookupRequest
	2, // 2: geoip.v1.GeoIPService.BatchLookup:input_type -> geoip.v1.BatchLookupRequest
	4, // 3: geoip.v1.GeoIPService.MyIP:input_type -> geoip.v1.MyIPRequest
	5, // 4: geoip.v1.GeoIPService.GetDBInfo:input_type -> geoip.v1.DBInfoRequest
	1, // 5: geoip.v1.GeoIPService.Lookup:output_type -> geoip.v1.LookupResponse
	3, // 6: geoip.v1.GeoIPService.BatchLookup:output_type -> geoip.v1.BatchLookupResponse
	1, // 7: geoip.v1.GeoIPService.MyIP:output_type -> geoip.v1.LookupResponse
	6, // 8: geoip.v1.GeoIPService.GetDBInfo:output_type -> geoip.v1.DBInfoResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_geoip_proto_geoip_proto_init() }
func file_internal_geoip_proto_geoip_proto_init() {
	if File_internal_geoip_proto_geoip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_geoip_proto_geoip_proto_rawDesc), len(file_internal_geoip_proto_geoip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_geoip_proto_geoip_proto_goTypes,
		DependencyIndexes: file_internal_geoip_proto_geoip_proto_depIdxs,
		MessageInfos:      file_internal_geoip_proto_geoip_proto_msgTypes,
	}.Build()
	File_internal_geoip_proto_geoip_proto = out.File
	file_internal_geoip_proto_geoip_proto_goTypes = nil
	file_internal_geoip_proto_geoip_proto_depIdxs = nil
}
