export const CONFIG = {
  HISTORY: {
    MAX_UNDO_ENTRIES: 100,
  },
  SIMULATION: {
    TICK_INTERVAL_SEC: 0.1,
    MAX_CHART_POINTS: 3000,
    DEFAULT_DURATION_SEC: 300,
    SNAPSHOT_EVERY_N_TICKS: 5,
  },
  UI: {
    DEBOUNCE_SAVE_MS: 500,
    LABEL_MAX_LENGTH: 100,
    CONFIG_VALUE_MAX_LENGTH: 500,
  },
  CANVAS: {
    SNAP_GRID: 15,
    DEFAULT_EDGE_STROKE_WIDTH: 2,
    CONTAINER_DEFAULT_WIDTH: 400,
    CONTAINER_DEFAULT_HEIGHT: 300,
    CONTAINER_MIN_WIDTH: 300,
    CONTAINER_MIN_HEIGHT: 200,
    CONTAINER_PADDING_LEFT: 10,
    CONTAINER_PADDING_TOP: 35,
  },
} as const;
